backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

site_url: https://danielgalan.dev

#publish_mode: editorial_workflow
#media_folder: assets/uploads
#public_folder: /static/uploads


local_backend: true
media_folder: static/img
public_folder: /img


collections:
  - name: 'post'
    label: 'Posts'
    label_singular: 'Post'
    folder: 'content/blog'
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    #path: '{{title}}/{{slug}}'
    #media_folder: ''
    #public_folder: ''
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          date_format: 'YYYY-MM-DD',
          time_format: 'HH:mm',
          format: 'YYYY-MM-DD HH:mm',
        }
      - { label: 'Description', name: 'description', widget: 'string' }
      - label: 'Cover Image'
        name: 'image'
        widget: 'image'
        required: false
        tagname: ''

      - { label: 'Body', name: 'body', widget: 'markdown' }